services:
  database:
    image: "postgres"
    container_name: postgres
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  backend:
#    container_name: spring_app
#    build:
#      context: ./spring_app
#    volumes:
#      - ./spring_app/src:/app/src
#    ports:
#      - "8080:8080"
#    command: sh ./docker-entrypoint.sh
#    depends_on:
#      - database
#    networks:
#      - app-network

  frontend:
    container_name: react_app
    build:
      context: ./react_app
    ports:
      - "3000:3000"
#    depends_on:
#      - backend
    networks:
      - app-network
    volumes:
      - ./react_app/src:/app/src
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
