services:
  frontend-dev:
    container_name: react_app
    build:
      context: ./react_app
      target: builder
    ports:
      - "5173:5173"
    volumes:
      - ./react_app:/app
      - /app/node_modules
    command: bun run dev --host
    environment:
      - VITE_HOST=0.0.0.0

  # frontend:
  #   build:
  #     context: ./react_app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./react_app:/app
  #     - /app/node_modules

  backend-dev:
    container_name: spring_app
    build:
      context: ./spring_app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005" # for remote debugging
    volumes:
      - ./spring_app:/app
      - ~/.m2:/root/.m2
    # command: sh /app/docker-entrypoint.sh
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # database:
  #   image: "postgres"
  #   container_name: postgres
  #   environment:
  #     - "POSTGRES_DB=mydatabase"
  #     - "POSTGRES_PASSWORD=secret"
  #     - "POSTGRES_USER=myuser"
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - app-network
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
